window.CHECKUP_FILES = [
{
"id": "F001",
"name": "2024年8月合作商站点检查管理办法.pdf",
"group": "site",
"topic": "站点检查管理",
"date": "2024-08-01",
"size_mb": 8.4,
"ext": ".pdf",
"url": "file:///D:/MT/奖惩类/2024年8月合作商站点检查管理办法.pdf",
"indexed": true,
"pages": 29
},
{
"id": "F002",
"name": "2025年9月专送合作商站点建设管理标准.jpg",
"group": "site",
"topic": "站点建设管理标准",
"date": "2025-09-01",
"size_mb": 20.4,
"ext": ".jpg",
"url": "file:///D:/MT/奖惩类/2025年9月专送合作商站点建设管理标准.jpg",
"indexed": false,
"pages": 0
},
{
"id": "F003",
"name": "2026年3-8权益.pdf",
"group": "insure",
"topic": "3-8权益",
"date": "2026-01-01",
"size_mb": 79.3,
"ext": ".pdf",
"url": "file:///D:/MT/奖惩类/2026年3-8权益.pdf",
"indexed": false,
"pages": 0
},
{
"id": "F004",
"name": "2026年9月1日-2027年8月31日专送合作商骑手保障补贴考核方案.pdf",
"group": "insure",
"topic": "保障补贴考核方案",
"date": "2026-09-01",
"size_mb": 2.7,
"ext": ".pdf",
"url": "file:///D:/MT/奖惩类/2026年9月1日-2027年8月31日专送合作商骑手保障补贴考核方案.pdf",
"indexed": true,
"pages": 8
},
{
"id": "F005",
"name": "410期-《本月新知-站外宿舍管理专项》.pdf",
"group": "safety",
"topic": "410期-《本月知-站外宿舍管理》",
"date": "2025-06-15",
"size_mb": 2.5,
"ext": ".pdf",
"url": "file:///D:/MT/奖惩类/410期-《本月新知-站外宿舍管理专项》.pdf",
"indexed": true,
"pages": 25
},
{
"id": "F006",
"name": "“加盟专属畅休卡”解读.pdf",
"group": "insure",
"topic": "“加盟专属畅休卡”",
"date": "2024-06-23",
"size_mb": 0.4,
"ext": ".pdf",
"url": "file:///D:/MT/奖惩类/“加盟专属畅休卡”解读.pdf",
"indexed": true,
"pages": 6
},
{
"id": "F007",
"name": "《早交流会管理重点SOP》.pptx",
"group": "sop",
"topic": "《管理重点》",
"date": "2024-04-10",
"size_mb": 2.6,
"ext": ".pptx",
"url": "file:///D:/MT/奖惩类/《早交流会管理重点SOP》.pptx",
"indexed": true,
"pages": 27
},
{
"id": "F008",
"name": "专送合作商配送人员安全管控标准.pdf",
"group": "safety",
"topic": "配送人员安全管控",
"date": "2025-05-08",
"size_mb": 3.1,
"ext": ".pdf",
"url": "file:///D:/MT/奖惩类/专送合作商配送人员安全管控标准.pdf",
"indexed": false,
"pages": 1
},
{
"id": "F009",
"name": "专送合作商配送人员薪酬保障管理标准V3.pdf",
"group": "insure",
"topic": "配送人员薪酬保障V3",
"date": "2024-06-24",
"size_mb": 4.6,
"ext": ".pdf",
"url": "file:///D:/MT/奖惩类/专送合作商配送人员薪酬保障管理标准V3.pdf",
"indexed": true,
"pages": 16
},
{
"id": "F010",
"name": "二、非公、异常剔除、安全及其他场景违规方案文件.pos",
"group": "safety",
"topic": "二、非公、异常剔除、安全及其他场景违规文件",
"date": "2025-08-31",
"size_mb": 0.1,
"ext": ".pos",
"url": "file:///D:/MT/奖惩类/二、非公、异常剔除、安全及其他场景违规方案文件.pos",
"indexed": false,
"pages": 0
},
{
"id": "F011",
"name": "交通申诉-更新版.pdf",
"group": "assess",
"topic": "交通申诉-",
"date": "2025-10-15",
"size_mb": 2.2,
"ext": ".pdf",
"url": "file:///D:/MT/奖惩类/交通申诉-更新版.pdf",
"indexed": true,
"pages": 18
},
{
"id": "F012",
"name": "兴达装备系统操作手册(2).pptx",
"group": "equip",
"topic": "兴达装备操作",
"date": "2024-10-04",
"size_mb": 3.4,
"ext": ".pptx",
"url": "file:///D:/MT/奖惩类/兴达装备系统操作手册(2).pptx",
"indexed": true,
"pages": 12
},
{
"id": "F013",
"name": "加盟商线下车辆管理标准.pdf",
"group": "equip",
"topic": "加盟商线下车辆",
"date": "2025-01-08",
"size_mb": 9.4,
"ext": ".pdf",
"url": "file:///D:/MT/奖惩类/加盟商线下车辆管理标准.pdf",
"indexed": true,
"pages": 13
},
{
"id": "F014",
"name": "合作商安全管理办法新.pdf",
"group": "safety",
"topic": "安全管理办法",
"date": "2026-03-11",
"size_mb": 14.6,
"ext": ".pdf",
"url": "file:///D:/MT/奖惩类/合作商安全管理办法新.pdf",
"indexed": false,
"pages": 1
},
{
"id": "F015",
"name": "合作商标准化检查管理办法-2025年1月(OCR).pdf",
"group": "site",
"topic": "标准化检查管理办法",
"date": "2025-01-01",
"size_mb": 26.1,
"ext": ".pdf",
"url": "file:///D:/MT/奖惩类/合作商标准化检查管理办法-2025年1月(OCR).pdf",
"indexed": true,
"pages": 28
},
{
"id": "F016",
"name": "合作商骑手载具安全管理标准.pdf",
"group": "safety",
"topic": "载具安全管理标准",
"date": "2026-09-11",
"size_mb": 2.8,
"ext": ".pdf",
"url": "file:///D:/MT/奖惩类/合作商骑手载具安全管理标准.pdf",
"indexed": false,
"pages": 12
},
{
"id": "F017",
"name": "宿舍安全卫生值日签到表.xlsx",
"group": "safety",
"topic": "宿舍安全卫生值日签到表",
"date": "2025-11-09",
"size_mb": 0.0,
"ext": ".xlsx",
"url": "file:///D:/MT/奖惩类/宿舍安全卫生值日签到表.xlsx",
"indexed": true,
"pages": 1
},
{
"id": "F018",
"name": "带刀检核流程-20250812.pptx",
"group": "safety",
"topic": "带刀检核-05081",
"date": "2025-09-10",
"size_mb": 10.7,
"ext": ".pptx",
"url": "file:///D:/MT/奖惩类/带刀检核流程-20250812.pptx",
"indexed": true,
"pages": 7
},
{
"id": "F019",
"name": "智能头盔试点城市考核管理标准.pdf",
"group": "equip",
"topic": "智能头盔考核管理标准",
"date": "2026-06-16",
"size_mb": 2.4,
"ext": ".pdf",
"url": "file:///D:/MT/奖惩类/2026-6新下载/智能头盔试点城市考核管理标准.pdf",
"indexed": false,
"pages": 1
},
{
"id": "F020",
"name": "智能血压仪培训课件.pptx",
"group": "sop",
"topic": "智能血压仪",
"date": "2025-05-02",
"size_mb": 159.2,
"ext": ".pptx",
"url": "file:///D:/MT/奖惩类/智能血压仪培训课件.pptx",
"indexed": false,
"pages": 0
},
{
"id": "F021",
"name": "智能血压仪联网教程-20250425 1.png",
"group": "sop",
"topic": "智能血压仪联网-050451",
"date": "2025-05-01",
"size_mb": 0.7,
"ext": ".png",
"url": "file:///D:/MT/奖惩类/智能血压仪联网教程-20250425 1.png",
"indexed": false,
"pages": 0
},
{
"id": "F022",
"name": "月站点标准化迭代.pptx",
"group": "site",
"topic": "月站点化",
"date": "2025-06-30",
"size_mb": 2.6,
"ext": ".pptx",
"url": "file:///D:/MT/奖惩类/月站点标准化迭代.pptx",
"indexed": true,
"pages": 17
},
{
"id": "F023",
"name": "空中课堂24年10月站点标准化宣导-早会消毒-20241022 4.pptx",
"group": "site",
"topic": "空中课堂4年10月站点化--04104",
"date": "2024-10-30",
"size_mb": 7.8,
"ext": ".pptx",
"url": "file:///D:/MT/奖惩类/空中课堂24年10月站点标准化宣导-早会消毒-20241022 4.pptx",
"indexed": true,
"pages": 19
},
{
"id": "F024",
"name": "专送合作商配送人员换电服务管标准.pdf",
"group": "equip",
"topic": "配送人员换电服务管",
"date": "2026-06-16",
"size_mb": 3.8,
"ext": ".pdf",
"url": "file:///D:/MT/奖惩类/2026-6新下载/专送合作商配送人员换电服务管标准.pdf",
"indexed": false,
"pages": 1
},
{
"id": "F025",
"name": "专送合作商配送人员车电租货管理标准.pdf",
"group": "equip",
"topic": "配送人员车电租货",
"date": "2026-06-16",
"size_mb": 4.4,
"ext": ".pdf",
"url": "file:///D:/MT/奖惩类/2026-6新下载/专送合作商配送人员车电租货管理标准.pdf",
"indexed": false,
"pages": 1
},
{
"id": "F026",
"name": "专送合作商骑手诉讼案件管理规范.pdf",
"group": "assess",
"topic": "骑手诉讼案件管理",
"date": "2026-06-16",
"size_mb": 3.9,
"ext": ".pdf",
"url": "file:///D:/MT/奖惩类/2026-6新下载/专送合作商骑手诉讼案件管理规范.pdf",
"indexed": false,
"pages": 1
},
{
"id": "F027",
"name": "专送站点基础建设系统提交说明.pdf",
"group": "site",
"topic": "站点基础建设",
"date": "2026-06-16",
"size_mb": 18.4,
"ext": ".pdf",
"url": "file:///D:/MT/奖惩类/2026-6新下载/专送站点基础建设系统提交说明.pdf",
"indexed": false,
"pages": 1
},
{
"id": "F028",
"name": "加盟商站智能化血压测压考核管理标准.pdf",
"group": "assess",
"topic": "加盟商站智能化血压测压考核",
"date": "2026-06-16",
"size_mb": 3.1,
"ext": ".pdf",
"url": "file:///D:/MT/奖惩类/2026-6新下载/加盟商站智能化血压测压考核管理标准.pdf",
"indexed": false,
"pages": 1
},
{
"id": "F029",
"name": "合作商装备穿戴管理标准.pdf",
"group": "equip",
"topic": "装备穿戴",
"date": "2026-06-16",
"size_mb": 4.1,
"ext": ".pdf",
"url": "file:///D:/MT/奖惩类/2026-6新下载/合作商装备穿戴管理标准.pdf",
"indexed": false,
"pages": 1
},
{
"id": "F030",
"name": "合作商风控管理标准.pdf",
"group": "assess",
"topic": "风控",
"date": "2026-06-16",
"size_mb": 2.5,
"ext": ".pdf",
"url": "file:///D:/MT/奖惩类/2026-6新下载/合作商风控管理标准.pdf",
"indexed": false,
"pages": 1
},
{
"id": "F031",
"name": "2024年8月薪动力专送合作商站点星级考核制度-普适版.pdf",
"group": "site",
"topic": "薪动力站点星级考核-",
"date": "2024-08-01",
"size_mb": 6.5,
"ext": ".pdf",
"url": "file:///D:/MT/奖惩类/8月/2024年8月薪动力专送合作商站点星级考核制度-普适版.pdf",
"indexed": true,
"pages": 22
},
{
"id": "F032",
"name": "【参考课件】2024年8月加盟合作商异常单数据剔除规则.pptx",
"group": "sop",
"topic": "【参考】加盟异常单数据剔除",
"date": "2024-08-01",
"size_mb": 3.7,
"ext": ".pptx",
"url": "file:///D:/MT/奖惩类/8月/【参考课件】2024年8月加盟合作商异常单数据剔除规则.pptx",
"indexed": true,
"pages": 47
},
{
"id": "F033",
"name": "【参考课件】2024年非公平竞争管理办法.pptx",
"group": "assess",
"topic": "【参考】非公平竞争管理",
"date": "2024-01-01",
"size_mb": 1.0,
"ext": ".pptx",
"url": "file:///D:/MT/奖惩类/8月/【参考课件】2024年非公平竞争管理办法.pptx",
"indexed": true,
"pages": 26
},
{
"id": "F034",
"name": "【参考课件】专送合作商配送人员薪酬保障管理标准.pptx",
"group": "insure",
"topic": "【参考】配送人员薪酬保障",
"date": "2024-08-22",
"size_mb": 1.0,
"ext": ".pptx",
"url": "file:///D:/MT/奖惩类/8月/【参考课件】专送合作商配送人员薪酬保障管理标准.pptx",
"indexed": true,
"pages": 24
},
{
"id": "F035",
"name": "2026年8月骑手合规装备款式【专送】0730.pdf",
"group": "equip",
"topic": "合规装备款式",
"date": "2026-08-01",
"size_mb": 12.2,
"ext": ".pdf",
"url": "file:///D:/MT/奖惩类/装备合规文件/2026年8月骑手合规装备款式【专送】0730.pdf",
"indexed": true,
"pages": 78
}
];
